name: Build & publish awesome artifact
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

jobs:
  publish:
    name: Publish awesome artifact
    runs-on: ubuntu-latest
    steps:
      # uses: actions/checkout@v2
      # id: build_artifact
      - uses: RomanDavlyatshin/vvv-github-action@0.0.2
        with:
          github-access-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }} # supply your personal token
          action-type: 'add-version'
          version-component-id: 'improved-rotary-phone'
          version-tag: '1.2.3' # steps.build_artifact.outputs.version