name: Build & publish awesome artifact
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

jobs:
  publish:
    name: Publish awesome artifact
    runs-on: ubuntu-latest
    steps:
      # - name: 'checkout'
      #   uses: actions/checkout@v2
      # - name: 'build'
      #   id: 'build_artifact'
      - id: 'build_artifact'
        run: |
          echo "::set-output name=name::improved-rotary-phone"
          echo "::set-output name=version::3.4.5"
      - uses: Drill4J/vee-table@0.0.0
        with:
          github-access-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }} # supply your personal token
          action-type: 'add-version'
          
          ledger-repo-url: 'https://github.com/Drill4J/vee-ledger'
          ledger-repo-owner: 'Drill4J'
          ledger-repo-name: 'vee-ledger'
          
          version-component-id: ${{ github.event.repository.name }}
          # version-component-id: ${{ steps.build_artifact.outputs.name }}
          version-tag: ${{ steps.build_artifact.outputs.version }}