# Put this into repository with your _E2E tests_
name: Run tests

on:
  # just for EXAMPLE
  workflow_dispatch:
  # just for EXAMPLE

jobs:
  publish:
    name: Run my tests
    runs-on: ubuntu-latest
    steps:
      
      # MOCK - example test run step
      - id: 'run_tests'
        run: |
          echo "::set-output name=setup_id::example"
          echo "::set-output name=status::failed"
          echo ::set-output name=env::'{"improved-rotary-phone":"1.0.0-1"}'
      # MOCK - example test run step
      
      # place this action LAST
      - uses: Drill4J/vee-table@0.0.0
        with:
          # leave everything "as-is"
          github-access-token: ${{ secrets.VEE_TABLE_TOKEN }}
          action-type: 'add-test-result'
          ledger-repo-url: 'https://github.com/Drill4J/vee-ledger'
          ledger-repo-owner: 'Drill4J'
          ledger-repo-name: 'vee-ledger'
          test-setup-id: ${{ github.event.repository.name }}
          # leave everything "as-is"

          # steps.run_tests is your test step name (defined above)
          test-status: ${{ steps.run_tests.outputs.status }} # 1. Pass test status (any string)
          test-component-version-map: ${{ steps.run_tests.outputs.env }} # 2. Pass JSON with componentId:version. Example: {"admin": "0.8.0", "admin-root-config": "0.8.1", "test2code-ui": "0.8.3"}
